accounts/urls.py
from django.urls import path

urlpatterns = [

]

bot_tasks/urls.py
from django.urls import path
from bot_tasks import views

app_name = 'bot_tasks'

urlpatterns = [
    path('', views.PendingTasks.as_view(), name='pending-tasks'),
    path('<slug:slug>/select_task/', views.TaskSelectView.as_view(), name='task-select'),
    # TODO -> Each of the individual tasks
    path('<slug:slug>/new_unfollow_non_followers_task/', views.CreateUnfollowNonFollowersTask.as_view(), name='create-unfollow-non-followers-task')
]

tweetcheat/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('', include('twitter_accounts.urls')),
    path('operations/', include('bot_tasks.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twitter_accounts/urls.py
from django.urls import path
from twitter_accounts import views

app_name = 'twitter_accounts'

urlpatterns = [
    path('', views.HomeView.as_view(), name='home'),
    path('add_twitter_account/', views.CreateTwitterAccountView.as_view(), name='add-twitter-account'),
    # path('twitter_account/<slug:slug>/', views.TwitterAccountDetail.as_view(), name='twitter-account-detail'),
    path('twitter_account/<slug:slug>/delete/', views.TwitterAccountDelete.as_view(), name='twitter-account-delete')
]

accounts/models.py
from django.db import models

# Create your models here.

bot_tasks/models.py
from django.db import models

from twitter_accounts.models import TwitterAccount


class BotTask(models.Model):
    """
    An abstract base class that we can extends for each type of bot operation
    that we want to create...
    """
    PENDING = 'PD'
    COMPLETE = 'CP'
    FAILED = 'FD'

    TASK_STATUS_CHOICES = (
        (PENDING, 'Pending'),
        (COMPLETE, 'Complete'),
        (FAILED, 'Failed'),
    )

    twitter_account = models.ForeignKey(TwitterAccount, on_delete=models.CASCADE)
    task_status = models.CharField(max_length=2, choices=TASK_STATUS_CHOICES)
    task_name = models.CharField(max_length=120)

    class Meta:
        abstract = True

    def __unicode__(self):
        return self.task_name

    def __str__(self):
        return self.task_name


class UnfollowNonFollowersTask(BotTask):
    """
    Inherits from BotTask

    This bot task defines an operation that will unfollow any accounts
    that the twitter account is following, if they don't also follow the account
    """
    pass

twitter_accounts/models.py
from django.conf import settings
from django.db import models
from django.db.models.signals import pre_save
from django.shortcuts import reverse
from django.utils.text import slugify


class TwitterAccount(models.Model):
    """
    Defines a twitter account
    """
    owned_by = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    # TODO We are not currently creating a slug
    slug = models.SlugField(unique=True)
    consumer_key = models.CharField(max_length=300)
    consumer_secret = models.CharField(max_length=300)
    access_token = models.CharField(max_length=300)
    access_secret = models.CharField(max_length=300)
    twitter_handle = models.CharField(max_length=300)

    def __unicode__(self):
        return self.twitter_handle

    def __str__(self):
        return self.twitter_handle

    def get_delete_url(self):
        return reverse('twitter_accounts:twitter-account-delete', kwargs={'slug': self.slug })

    def get_create_task_url(self):
        return reverse('bot_tasks:task-select', kwargs={'slug': self.slug })


def create_twitter_account_slug(instance, new_slug=None):
    """
    Creates a new twitter account slug
    """
    slug = slugify(instance.twitter_handle)
    if new_slug is not None:
        slug = new_slug
    qs = TwitterAccount.objects.filter(slug=slug).order_by('id')
    if qs.exists():
        new_slug = "%s-%s" % (slug, qs.first().id)
        return create_twitter_account_slug(instance, new_slug=new_slug)
    return slug


def pre_save_twitter_account_receiver(sender, instance, *args, **kwargs):
    """
    Called when a twitter account is saved
    """
    if not instance.slug:
        instance.slug = create_twitter_account_slug(instance)

pre_save.connect(pre_save_twitter_account_receiver, sender=TwitterAccount)

twitter_accounts/forms.py
from django import forms

from twitter_accounts.models import TwitterAccount


# TODO -> Shall we have them add their own twitter handle or can we just pull this???
class TwitterAccountForm(forms.ModelForm):
    class Meta:
        model = TwitterAccount
        fields = [
            'twitter_handle',
            'consumer_key',
            'consumer_secret',
            'access_token',
            'access_secret',
        ]

accounts/views.py
from django.shortcuts import render

# Create your views here.

bot_tasks/views.py
from django.shortcuts import render
from django.views.generic import ListView, TemplateView
from django.views.generic.edit import FormView

from bot_tasks.models import (
    BotTask,
    UnfollowNonFollowersTask
)

class PendingTasks(ListView):
    model = BotTask
    context_object_name = 'bot_task_list'
    template_name = 'bot_tasks/bot_tasks.html'

    def get_context_data(self, *args, **kwargs):
        context = super(PendingOperations, self).get_context_data(**kwargs)
        title = 'Recent pending operations'
        return context

    def get_queryset(self, *args, **kwargs):
        # TODO -> Filter by the user
        queryset = BotTask.objects.all()
        return queryset


class TaskSelectView(TemplateView):
    """
    A template view that allows users to select which type of task
    they want to create.
    """
    template_name = 'bot_tasks/task_to_create.html'

    def get_context_data(self, *args, **kwargs):
        context = super(TaskSelectView, self).get_context_data(*args, **kwargs)
        return context

class CreateUnfollowNonFollowersTask(FormView):
    pass

twitter_accounts/views.py
from django.contrib import messages
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView
from django.views.generic.edit import DeleteView, FormView
from twitter_accounts.models import TwitterAccount
from twitter_accounts.forms import TwitterAccountForm
from bot_tasks.models import BotTask


class HomeView(ListView):
    """
    The home view should show a list of the users accounts
    """
    model = TwitterAccount
    context_object_name = 'twitter_account_list'
    template_name = 'twitter_accounts/home.html'

    def get_context_data(self, *args, **kwargs):
        context = super(HomeView, self).get_context_data(**kwargs)
        return context

    def get_queryset(self, *args, **kwargs):
        # TODO Filter by the user
        queryset = TwitterAccount.objects.all()
        return queryset


class CreateTwitterAccountView(FormView):
    """
    Allows the user to create a twitter account
    """
    template_name = 'twitter_accounts/twitter_account_form.html'
    form_class = TwitterAccountForm
    success_url = '/'

    # TODO -> Is there anything else that we want to do if the form is not valid??
    # TODO Think that I will need to save and commit the form here?? Does it do it itself? probably not
    def form_valid(self, form):
        instance = form.save(commit=False)
        instance.owned_by = self.request.user
        instance.save()
        messages.success(self.request, 'Your Twitter account has been added successfully')
        return super().form_valid(form)


class TwitterAccountDelete(DeleteView):
    model = TwitterAccount
    success_url = reverse_lazy('home')

bot_tasks/templates/bot_tasks/bot_tasks.html
{% extends 'base.html' %}
{% block content %}
<h1>Tasks you've given our wonderful bot!<h1>
{% endblock content %}

bot_tasks/templates/bot_tasks/task_to_create.html
{% extends "base.html" %}
{% block content %}

<div class="row">
  <!-- Unfollow non followers -->
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <h2 class="card-title">Unfollow Non Followers</h2>
        <p>This task will unfollow any account that you follow that does not also follow you back.</p>
        <a href="#" class="btn btn-primary">Create Task</a>
      </div>
    </div>
  </div>

  <!-- Follow the followers -->
  <div class="col-md-4">
    <div class="card">
      <div class="card-body">
        <h2 class="card-title">Follow the followers of another account</h2>
        <p>This task will follow all the accounts that follow a specified account</p>
        <a href="#" class="btn btn-primary">Create Task</a>
      </div>
    </div>
  </div>
</div>

{% endblock content %}

templates/base.html
{%load staticfiles %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href={% static 'css/style.css'%}>
    <title>SquakBot</title>
    {% block extra_style %}{% endblock extra_style %}
  </head>
  <body>
    {% include 'navbar.html' %}
    {% include 'alerts.html' %}
    <div class="container pt-3">
      {% block content %}{% endblock content %}
    </div>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    {% block extra_script %}{% endblock extra_script %}
  </body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark" style="background-color: #794bc4">
  <a class="navbar-brand" href="#">Squak Bot</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'twitter_accounts:home' %}">Home</a>
      </li>
      <li class="nav-item active">
        <a class="nav-link" href="{% url 'twitter_accounts:add-twitter-account' %}">Add Twitter Account</a>
      </li>

      <li class="nav-item active">
        <a class="nav-link" href="{% url 'bot_tasks:pending-tasks' %}">Operations</a>
      </li>

    </ul>
  </div>
</nav>

twitter_accounts/templates/twitter_accounts/home.html
{% extends "base.html" %}
{% block content %}
  <h1>Your Twitter Accounts</h1>
  <hr/>
  {% if twitter_account_list %}
  {% for twitter_account in twitter_account_list %}
    <div class="card">
      <div class="card-body">
        <h3 class="card-title">@{{twitter_account.twitter_handle}}</h3>
        <div class="card-body">
          <p><b>Public Consumer Key: </b> {{ twitter_account.consumer_key }}</p>
          <p><b>Private Consumer Key: </b> {{ twitter_account.consumer_secret }}</p>
          <p><b>Public Access Token: </b> {{ twitter_account.access_token }}</p>
          <p><b>Private Access Token: </b> {{ twitter_account.access_secret }}</p>
        </div>
        <a href="{{ twitter_account.get_create_task_url }}" class="btn btn-primary">New Task</a>
        <a href="{{ twitter_account.get_delete_url }}" class="btn btn-danger">Delete Account</a>

      </div>
    </div>
  {% endfor %}

  {% else %}
    <p>No twitter accounts found</p>
  {% endif %}


  <h1>Your Recent Operations</h1>
  <hr/>
  {% if bot_tasks %}
  {% for task in bot_tasks %}
  {% endfor %}
  {% endif %}



{% endblock content %}

twitter_accounts/templates/twitter_accounts/twitter_account_confirm_delete.html
<form method="post">
  {% csrf_token %}
  <p>Are you sure that you want to delete "{{ object }}"?</p>
  <input type="submit" class="btn btn-danger" value="Confirm"/>
</form>

twitter_accounts/templates/twitter_accounts/twitter_account_form.html
{% extends 'base.html' %}
{% load widget_tweaks %}
{% block content %}

<div class="row">
  <div class="col-md-8">
    <h1>Add New Twitter Account</h1>
    <p>Adding a new twitter account will allow you to perform actions on it using our bot. We do not require your password for this.</p>

    <form action="" method="POST">
      {% csrf_token %}
      <div class="form-group">
        {% render_field form.twitter_handle class="form-control" placeholder="Twitter Handle" %}
      </div>
      <div class="form-group">
        {% render_field form.consumer_key class="form-control" placeholder="Consumer Public Key" %}
      </div>
      <div class="form-group">
        {% render_field form.consumer_secret class="form-control" placeholder="Consumer Private Key" %}
      </div>
      <div class="form-group">
        {% render_field form.access_token class="form-control" placeholder="Access Public Token" %}
      </div>
      <div class="form-group">
        {% render_field form.access_secret class="form-control" placeholder="Access Secret Token" %}
      </div>
      <button type="submit" class="btn btn-primary">Add Twitter Account</button>
    </form>
  </div>

  <div class="col-md-4">
    <h2>How does this work?</h2>
    <p>
      Follow the instructions <a href='#'>here</a> to get the data that we need.
    </p>
    <hr/>
    <p>
      The keys here allows our twitter bot to perform actions on your account without you needing to release your
      password to us. This helps to keep your account secure, while giving our bot the access level that it needs to your
      twitter account to perform actions such as mass following certain users, unfollowing users that aren't following you.
      Mass dm'ing users that follow you, etc. Tweet Cheat is basically the social media manager that doesn't come with the 50k /year wage.
    </p>
    <hr/>
    <p>

    </p>
  </div>
</div>
{% endblock content %}